### ISSUE TITLE
Should documentation be made for save files

### ISSUE THREAD

**Issue by BrianTheBrain11** [byt3m/Valheim-Character-Editor#32]
question: 
Should documentation be made analyzing save file composition, and if so where?
I'm trying my hand out on working on a public repo, and I'm analyzing the file with a hex editor and am able to put a bit of it together, so hopefully I'll be able to contribute.

**Comment by FakeMichau** [comment]
I was the one who reverse engineered by looking at the game code. You can take a look at Parser.cs. There are some things that I omitted such as checking the data version in numerous places (code only reads them as it's necessary). 
The documentation would be a mess because the save structure is a total mess. IMO the developer should've used Unity's build-in tools for creating saves and not create their own (that can take tens of MB if you play on multiple worlds). 
If you want to make documentation - feel free to do so.
